### ISSUE TITLE
Buildroot Bringup

### ISSUE THREAD

**Issue by HARSH1911RATHORE** [cu-ecen-5013/final-project-HARSH1911RATHORE#1]
Buildroot setup for Raspberry Pi  that builds an image for it- In progress

DOD- GETTING IMAGE WITH ALL REQUIRED PACKAGES TO BE LOADED INTO RPI

**Comment by HARSH1911RATHORE** [comment]
WAS ABLE TO LOAD THE REQUIRED MODULES WHICH INCLUDE I2C DEV, UART AND ADDITIONAL MODULES LIKE WIFI AND DEBUGGING TOOLS LIKE STRACE SUCCESSFULLY

**Comment by HARSH1911RATHORE** [comment]
Link to the closed issue commit - https://github.com/cu-ecen-5013/final-project-HARSH1911RATHORE
d0ff0b735c3252d159d1c9ec2480c57fb38caddf

**Comment by steveantony5** [comment]
@HARSH1911RATHORE  Please edit the first comment and move the dod there
Refer: https://docs.google.com/document/d/1nHiCKOrHSQBuZVDpSXKqPFwV5W3lHyvE4heCGnz7ghw/edit referencing step 3.f

**Comment by HARSH1911RATHORE** [comment]
Edited as required

Regards,
Harsh Rathore
