### ISSUE TITLE
Sprint 3

### ISSUE THREAD

**Issue by HARSH1911RATHORE** [cu-ecen-5013/final-project-HARSH1911RATHORE#3]
Fetch current temperature readings from the Si7021 sensor which is sent via Uart to the beaglebone. Fine-tune the uart to send the temperature measured from the sensor to the beaglebone.  Set the correct delay values to be able to send to the beaglebone which will display the data onto the host machine. Look into the timing of sending the data values which will be compared by beaglebone and arduino temperature measurements to get the correct temperature values. 

DoD : Able to send updated temperature values to the beaglebone as and when required by beaglebone so that the temperature readings of all the boards are done together for proper fault detection

Blocker: None as of now

**Comment by HARSH1911RATHORE** [comment]
Update: The temperature obtained from i2c si7021 based sensor was updated with timestamps and was fed through the uart to obtain faulty detection of sensor which was done at the host beaglebone by comparison with the values obtained from various sensors. The temperature was updated after getting an acknowledgment from the host beaglebone which signals to start reading the value of the temperature reading. This was developed as a fault safety mechanism where the readings obtained from all the sensors are in synchronization and readings of a specific time are compared correctly to obtain accuracy in the read temperature data.  The verification was done using debug printf statements throughout the entire program

**Comment by HARSH1911RATHORE** [comment]
LINK TO THE APP CODE - https://github.com/cu-ecen-5013/final-project-Kushagra42 e6c4e66ee410bec299b06aa5e0f81eea9f183ac1
Buildroot - https://github.com/cu-ecen-5013/final-project-HARSH1911RATHORE 2ce0869c97dbd7344c7933a87c30e5fc9f87b571

**Comment by steveantony5** [comment]
@HARSH1911RATHORE  I could not find the commit id e6c4e66ee410bec299b06aa5e0f81eea9f183ac1

Can you please add a link to that commit. I wanted to look at the code you checked in for sprint 3

**Comment by steveantony5** [comment]
The code which you added as part for sprint 3 excluding sprint 1 and 2 work

**Comment by HARSH1911RATHORE** [comment]
Here it is Steve https://github.com/cu-ecen-5013/final-project-Kushagra42/commit/e6c4e66ee410bec299b06aa5e0f81eea9f183ac1
